### ISSUE TITLE
There is only voice Reading offered , then it stops reading the responses

### ISSUE THREAD

**Issue by BW-KING** [pazoff/Mycroft-Cat#1]
**Describe the bug**
When i create my first request in the chat , it successfully reads the response out loud after the message is typed out, however when i submit any followup questions it fails to read

**To Reproduce**
1. Go to '...' Enable the plugin - the goto the chat window home
2. Click on '....' -- create a Query
3. Scroll down to '....' after the first query is read submit a second

**Expected behavior**

**Additional context**
it would be great if there was options in the pluigin settings to manage the speed and the voice being used. and also could provide error checking.

**Comment by pazoff** [comment]
> it would be great if there was options in the pluigin settings to manage the speed and the voice being used.

This functionality is about to be implemented in the next version.

**Comment by pazoff** [comment]
> **Describe the bug** When i create my first request in the chat , it successfully reads the response out loud after the message is typed out, however when i submit any followup questions it fails to read
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '...' Enable the plugin - the goto the chat window home
> 
>     2. Click on '....' -- create a Query
> 
>     3. Scroll down to '....' after the first query is read submit a second
> 
>     4. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Additional context** it would be great if there was options in the pluigin settings to manage the speed and the voice being used. and also could provide error checking.



**UPDATED:** An option to select different speaker was added in languages English, Italian and Russian

**Comment by BW-KING** [comment]
> > **Describe the bug** When i create my first request in the chat , it successfully reads the response out loud after the message is typed out, however when i submit any followup questions it fails to read
> > **To Reproduce** Steps to reproduce the behavior:
> > ```
> > 1. Go to '...' Enable the plugin - the goto the chat window home
> > 
> > 2. Click on '....' -- create a Query
> > 
> > 3. Scroll down to '....' after the first query is read submit a second
> > 
> > 4. See error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Additional context** it would be great if there was options in the pluigin settings to manage the speed and the voice being used. and also could provide error checking.
> 
> **UPDATED:** An option to select different speaker was added in languages English, Italian and Russian

Wow you did a great Job and Quick - I believe this could easily be one of the biggest and most used plugins very soon. there are so many feautures that could be added to make this more awesome so I am so excited to see this grow and be apart of helping it!

**Comment by pazoff** [comment]
> > > **Describe the bug** When i create my first request in the chat , it successfully reads the response out loud after the message is typed out, however when i submit any followup questions it fails to read
> > > **To Reproduce** Steps to reproduce the behavior:
> > > ```
> > > 1. Go to '...' Enable the plugin - the goto the chat window home
> > > 
> > > 2. Click on '....' -- create a Query
> > > 
> > > 3. Scroll down to '....' after the first query is read submit a second
> > > 
> > > 4. See error
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Expected behavior** A clear and concise description of what you expected to happen.
> > > **Additional context** it would be great if there was options in the pluigin settings to manage the speed and the voice being used. and also could provide error checking.
> > 
> > 
> > **UPDATED:** An option to select different speaker was added in languages English, Italian and Russian
> 
> Wow you did a great Job and Quick - I believe this could easily be one of the biggest and most used plugins very soon. there are so many feautures that could be added to make this more awesome so I am so excited to see this grow and be apart of helping it!

You can visit [Discussions](https://github.com/pazoff/Mycroft-Cat/discussions) and suggest new features.
